### PR TITLE
LPS-84620

### PR DESCRIPTION
**Pull request by ifnazar**

### CODE REVIEW

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:sf

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:sf

**Comment by vagnerbc** [comment]
Aparentemente faltou o commit de um novo método addArticle na classe com.liferay.journal.test.util.search.JournalArticleSearchFixture.

**Comment by ifnazar** [comment]
ci:test:search

**Comment by ifnazar** [comment]
ci:test:search

**Pull request closed without merging**
